# Generated by Django 2.1.4 on 2018-12-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterField(
            model_name='computer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y', verbose_name='Картинка товара'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара'),
        ),
    ]
