# Generated by Django 2.1.4 on 2018-12-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181222_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, default='../static/images/comp_default.jpg', upload_to='products/%Y', verbose_name='Картинка товара'),
        ),
    ]
